/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTIC_WALL_PB_H_INCLUDED
#define PB_MESHTASTIC_WALL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

typedef struct _meshtastic_LoBBSWallCanvas {
    char cells[144];
    uint32_t crc32;
} meshtastic_LoBBSWallCanvas;

typedef struct _meshtastic_LoBBSWallSeen {
    uint64_t user_uuid;
    uint32_t last_crc32;
} meshtastic_LoBBSWallSeen;

typedef struct _meshtastic_LoBBSWallConfig {
    uint32_t period_seconds;
    uint32_t max_cells_per_cycle;
} meshtastic_LoBBSWallConfig;

typedef struct _meshtastic_LoBBSWallQuota {
    uint64_t user_uuid;
    uint32_t cycle_start;
    uint32_t cells_used;
} meshtastic_LoBBSWallQuota;

#ifdef __cplusplus
extern "C" {
#endif

#define meshtastic_LoBBSWallCanvas_init_default  {{0}, 0}
#define meshtastic_LoBBSWallSeen_init_default    {0, 0}
#define meshtastic_LoBBSWallConfig_init_default  {0, 0}
#define meshtastic_LoBBSWallQuota_init_default   {0, 0, 0}
#define meshtastic_LoBBSWallCanvas_init_zero     {{0}, 0}
#define meshtastic_LoBBSWallSeen_init_zero       {0, 0}
#define meshtastic_LoBBSWallConfig_init_zero     {0, 0}
#define meshtastic_LoBBSWallQuota_init_zero      {0, 0, 0}

#define meshtastic_LoBBSWallCanvas_cells_tag     1
#define meshtastic_LoBBSWallCanvas_crc32_tag     2
#define meshtastic_LoBBSWallSeen_user_uuid_tag   1
#define meshtastic_LoBBSWallSeen_last_crc32_tag  2
#define meshtastic_LoBBSWallConfig_period_seconds_tag 1
#define meshtastic_LoBBSWallConfig_max_cells_per_cycle_tag 2
#define meshtastic_LoBBSWallQuota_user_uuid_tag  1
#define meshtastic_LoBBSWallQuota_cycle_start_tag 2
#define meshtastic_LoBBSWallQuota_cells_used_tag 3

#define meshtastic_LoBBSWallCanvas_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    cells,             1) \
X(a, STATIC,   SINGULAR, UINT32,   crc32,             2)
#define meshtastic_LoBBSWallCanvas_CALLBACK NULL
#define meshtastic_LoBBSWallCanvas_DEFAULT NULL

#define meshtastic_LoBBSWallSeen_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   user_uuid,         1) \
X(a, STATIC,   SINGULAR, UINT32,   last_crc32,        2)
#define meshtastic_LoBBSWallSeen_CALLBACK NULL
#define meshtastic_LoBBSWallSeen_DEFAULT NULL

#define meshtastic_LoBBSWallConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   period_seconds,    1) \
X(a, STATIC,   SINGULAR, UINT32,   max_cells_per_cycle, 2)
#define meshtastic_LoBBSWallConfig_CALLBACK NULL
#define meshtastic_LoBBSWallConfig_DEFAULT NULL

#define meshtastic_LoBBSWallQuota_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   user_uuid,         1) \
X(a, STATIC,   SINGULAR, UINT32,   cycle_start,       2) \
X(a, STATIC,   SINGULAR, UINT32,   cells_used,        3)
#define meshtastic_LoBBSWallQuota_CALLBACK NULL
#define meshtastic_LoBBSWallQuota_DEFAULT NULL

extern const pb_msgdesc_t meshtastic_LoBBSWallCanvas_msg;
extern const pb_msgdesc_t meshtastic_LoBBSWallSeen_msg;
extern const pb_msgdesc_t meshtastic_LoBBSWallConfig_msg;
extern const pb_msgdesc_t meshtastic_LoBBSWallQuota_msg;

#define meshtastic_LoBBSWallCanvas_fields &meshtastic_LoBBSWallCanvas_msg
#define meshtastic_LoBBSWallSeen_fields &meshtastic_LoBBSWallSeen_msg
#define meshtastic_LoBBSWallConfig_fields &meshtastic_LoBBSWallConfig_msg
#define meshtastic_LoBBSWallQuota_fields &meshtastic_LoBBSWallQuota_msg

#define meshtastic_LoBBSWallCanvas_size            152
#define meshtastic_LoBBSWallSeen_size              17
#define meshtastic_LoBBSWallConfig_size            12
#define meshtastic_LoBBSWallQuota_size             22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
