/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "wall.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(meshtastic_LoBBSWallCanvas, meshtastic_LoBBSWallCanvas, AUTO)

PB_BIND(meshtastic_LoBBSWallSeen, meshtastic_LoBBSWallSeen, AUTO)


PB_BIND(meshtastic_LoBBSWallConfig, meshtastic_LoBBSWallConfig, AUTO)


PB_BIND(meshtastic_LoBBSWallQuota, meshtastic_LoBBSWallQuota, AUTO)
