/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTIC_MAIL_PB_H_INCLUDED
#define PB_MESHTASTIC_MAIL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* LoBBS Mail Record
 Stores mail messages between users
 UUID: auto-incrementing message ID */
typedef struct _meshtastic_LoBBSMail {
    /* Message UUID (auto-generated) */
    uint64_t uuid;
    /* Sender's user UUID */
    uint64_t from_user_uuid;
    /* Recipient's user UUID */
    uint64_t to_user_uuid;
    /* Message content (max 200 bytes) */
    char message[200];
    /* Timestamp when message was sent */
    uint32_t timestamp;
    /* Read status */
    bool read;
} meshtastic_LoBBSMail;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meshtastic_LoBBSMail_init_default        {0, 0, 0, "", 0, 0}
#define meshtastic_LoBBSMail_init_zero           {0, 0, 0, "", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define meshtastic_LoBBSMail_uuid_tag            1
#define meshtastic_LoBBSMail_from_user_uuid_tag  2
#define meshtastic_LoBBSMail_to_user_uuid_tag    3
#define meshtastic_LoBBSMail_message_tag         4
#define meshtastic_LoBBSMail_timestamp_tag       5
#define meshtastic_LoBBSMail_read_tag            6

/* Struct field encoding specification for nanopb */
#define meshtastic_LoBBSMail_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   uuid,              1) \
X(a, STATIC,   SINGULAR, UINT64,   from_user_uuid,    2) \
X(a, STATIC,   SINGULAR, UINT64,   to_user_uuid,      3) \
X(a, STATIC,   SINGULAR, STRING,   message,           4) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         5) \
X(a, STATIC,   SINGULAR, BOOL,     read,              6)
#define meshtastic_LoBBSMail_CALLBACK NULL
#define meshtastic_LoBBSMail_DEFAULT NULL

extern const pb_msgdesc_t meshtastic_LoBBSMail_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meshtastic_LoBBSMail_fields &meshtastic_LoBBSMail_msg

/* Maximum encoded size of messages (where known) */
#define MESHTASTIC_MAIL_PB_H_MAX_SIZE            meshtastic_LoBBSMail_size
#define meshtastic_LoBBSMail_size                243

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
