/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTIC_NEWS_PB_H_INCLUDED
#define PB_MESHTASTIC_NEWS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* LoBBS News Record
 Stores news/bulletin posts visible to all users
 UUID: auto-generated news ID */
typedef struct _meshtastic_LoBBSNews {
    /* News UUID (auto-generated) */
    uint64_t uuid;
    /* Author's user UUID */
    uint64_t author_user_uuid;
    /* News content (max 200 bytes) */
    char message[200];
    /* Timestamp when news was posted */
    uint32_t timestamp;
} meshtastic_LoBBSNews;

/* LoBBS News Read Tracking Record
 Tracks which users have read which news items
 UUID: deterministic key derived from news_uuid + user_uuid */
typedef struct _meshtastic_LoBBSNewsRead {
    /* News item UUID */
    uint64_t news_uuid;
    /* User UUID who read the news */
    uint64_t user_uuid;
    /* Timestamp when read */
    uint32_t read_timestamp;
} meshtastic_LoBBSNewsRead;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meshtastic_LoBBSNews_init_default        {0, 0, "", 0}
#define meshtastic_LoBBSNewsRead_init_default    {0, 0, 0}
#define meshtastic_LoBBSNews_init_zero           {0, 0, "", 0}
#define meshtastic_LoBBSNewsRead_init_zero       {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define meshtastic_LoBBSNews_uuid_tag            1
#define meshtastic_LoBBSNews_author_user_uuid_tag 2
#define meshtastic_LoBBSNews_message_tag         3
#define meshtastic_LoBBSNews_timestamp_tag       4
#define meshtastic_LoBBSNewsRead_news_uuid_tag   1
#define meshtastic_LoBBSNewsRead_user_uuid_tag   2
#define meshtastic_LoBBSNewsRead_read_timestamp_tag 3

/* Struct field encoding specification for nanopb */
#define meshtastic_LoBBSNews_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   uuid,              1) \
X(a, STATIC,   SINGULAR, UINT64,   author_user_uuid,   2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         4)
#define meshtastic_LoBBSNews_CALLBACK NULL
#define meshtastic_LoBBSNews_DEFAULT NULL

#define meshtastic_LoBBSNewsRead_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   news_uuid,         1) \
X(a, STATIC,   SINGULAR, UINT64,   user_uuid,         2) \
X(a, STATIC,   SINGULAR, UINT32,   read_timestamp,    3)
#define meshtastic_LoBBSNewsRead_CALLBACK NULL
#define meshtastic_LoBBSNewsRead_DEFAULT NULL

extern const pb_msgdesc_t meshtastic_LoBBSNews_msg;
extern const pb_msgdesc_t meshtastic_LoBBSNewsRead_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meshtastic_LoBBSNews_fields &meshtastic_LoBBSNews_msg
#define meshtastic_LoBBSNewsRead_fields &meshtastic_LoBBSNewsRead_msg

/* Maximum encoded size of messages (where known) */
#define MESHTASTIC_NEWS_PB_H_MAX_SIZE            meshtastic_LoBBSNews_size
#define meshtastic_LoBBSNewsRead_size            28
#define meshtastic_LoBBSNews_size                230

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
