/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTIC_LOBBS_PB_H_INCLUDED
#define PB_MESHTASTIC_LOBBS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(32) meshtastic_LoBBSUser_password_hash_t;
/* LoBBS User Record
 Stores user authentication information for the LoBBS system
 UUID: username (for direct lookups) */
typedef struct _meshtastic_LoBBSUser {
    /* Username for the user account */
    char username[32];
    /* SHA256 hash of the user's password (32 bytes) */
    meshtastic_LoBBSUser_password_hash_t password_hash;
    /* User UUID - deterministic hash derived from username */
    uint64_t uuid;
    /* Whether this user is an administrator */
    bool is_admin;
} meshtastic_LoBBSUser;

/* LoBBS Session Record
 Maps node IDs to logged-in user UUIDs
 UUID: node ID as uint64 */
typedef struct _meshtastic_LoBBSSession {
    /* User UUID of the logged-in user */
    uint64_t user_uuid;
    /* Last login timestamp */
    uint32_t last_login_time;
    /* Node ID (stored for reference) */
    uint32_t node_id;
} meshtastic_LoBBSSession;

/* LoBBS Mail Record
 Stores mail messages between users
 UUID: auto-incrementing message ID */
typedef struct _meshtastic_LoBBSMail {
    /* Message UUID (auto-generated) */
    uint64_t uuid;
    /* Sender's user UUID */
    uint64_t from_user_uuid;
    /* Recipient's user UUID */
    uint64_t to_user_uuid;
    /* Message content (max 200 bytes) */
    char message[200];
    /* Timestamp when message was sent */
    uint32_t timestamp;
    /* Read status */
    bool read;
} meshtastic_LoBBSMail;

/* LoBBS News Record
 Stores news/bulletin posts visible to all users
 UUID: auto-generated news ID */
typedef struct _meshtastic_LoBBSNews {
    /* News UUID (auto-generated) */
    uint64_t uuid;
    /* Author's user UUID */
    uint64_t author_user_uuid;
    /* News content (max 200 bytes) */
    char message[200];
    /* Timestamp when news was posted */
    uint32_t timestamp;
} meshtastic_LoBBSNews;

/* LoBBS News Read Tracking Record
 Tracks which users have read which news items
 UUID: deterministic key derived from news_uuid + user_uuid */
typedef struct _meshtastic_LoBBSNewsRead {
    /* News item UUID */
    uint64_t news_uuid;
    /* User UUID who read the news */
    uint64_t user_uuid;
    /* Timestamp when read */
    uint32_t read_timestamp;
} meshtastic_LoBBSNewsRead;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meshtastic_LoBBSUser_init_default        {"", {0, {0}}, 0, 0}
#define meshtastic_LoBBSSession_init_default     {0, 0, 0}
#define meshtastic_LoBBSMail_init_default        {0, 0, 0, "", 0, 0}
#define meshtastic_LoBBSNews_init_default        {0, 0, "", 0}
#define meshtastic_LoBBSNewsRead_init_default    {0, 0, 0}
#define meshtastic_LoBBSUser_init_zero           {"", {0, {0}}, 0, 0}
#define meshtastic_LoBBSSession_init_zero        {0, 0, 0}
#define meshtastic_LoBBSMail_init_zero           {0, 0, 0, "", 0, 0}
#define meshtastic_LoBBSNews_init_zero           {0, 0, "", 0}
#define meshtastic_LoBBSNewsRead_init_zero       {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define meshtastic_LoBBSUser_username_tag        1
#define meshtastic_LoBBSUser_password_hash_tag   2
#define meshtastic_LoBBSUser_uuid_tag            3
#define meshtastic_LoBBSUser_is_admin_tag        4
#define meshtastic_LoBBSSession_user_uuid_tag    1
#define meshtastic_LoBBSSession_last_login_time_tag 2
#define meshtastic_LoBBSSession_node_id_tag      3
#define meshtastic_LoBBSMail_uuid_tag            1
#define meshtastic_LoBBSMail_from_user_uuid_tag  2
#define meshtastic_LoBBSMail_to_user_uuid_tag    3
#define meshtastic_LoBBSMail_message_tag         4
#define meshtastic_LoBBSMail_timestamp_tag       5
#define meshtastic_LoBBSMail_read_tag            6
#define meshtastic_LoBBSNews_uuid_tag            1
#define meshtastic_LoBBSNews_author_user_uuid_tag 2
#define meshtastic_LoBBSNews_message_tag         3
#define meshtastic_LoBBSNews_timestamp_tag       4
#define meshtastic_LoBBSNewsRead_news_uuid_tag   1
#define meshtastic_LoBBSNewsRead_user_uuid_tag   2
#define meshtastic_LoBBSNewsRead_read_timestamp_tag 3

/* Struct field encoding specification for nanopb */
#define meshtastic_LoBBSUser_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   username,          1) \
X(a, STATIC,   SINGULAR, BYTES,    password_hash,     2) \
X(a, STATIC,   SINGULAR, UINT64,   uuid,              3) \
X(a, STATIC,   SINGULAR, BOOL,     is_admin,          4)
#define meshtastic_LoBBSUser_CALLBACK NULL
#define meshtastic_LoBBSUser_DEFAULT NULL

#define meshtastic_LoBBSSession_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   user_uuid,         1) \
X(a, STATIC,   SINGULAR, UINT32,   last_login_time,   2) \
X(a, STATIC,   SINGULAR, UINT32,   node_id,           3)
#define meshtastic_LoBBSSession_CALLBACK NULL
#define meshtastic_LoBBSSession_DEFAULT NULL

#define meshtastic_LoBBSMail_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   uuid,              1) \
X(a, STATIC,   SINGULAR, UINT64,   from_user_uuid,    2) \
X(a, STATIC,   SINGULAR, UINT64,   to_user_uuid,      3) \
X(a, STATIC,   SINGULAR, STRING,   message,           4) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         5) \
X(a, STATIC,   SINGULAR, BOOL,     read,              6)
#define meshtastic_LoBBSMail_CALLBACK NULL
#define meshtastic_LoBBSMail_DEFAULT NULL

#define meshtastic_LoBBSNews_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   uuid,              1) \
X(a, STATIC,   SINGULAR, UINT64,   author_user_uuid,   2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         4)
#define meshtastic_LoBBSNews_CALLBACK NULL
#define meshtastic_LoBBSNews_DEFAULT NULL

#define meshtastic_LoBBSNewsRead_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   news_uuid,         1) \
X(a, STATIC,   SINGULAR, UINT64,   user_uuid,         2) \
X(a, STATIC,   SINGULAR, UINT32,   read_timestamp,    3)
#define meshtastic_LoBBSNewsRead_CALLBACK NULL
#define meshtastic_LoBBSNewsRead_DEFAULT NULL

extern const pb_msgdesc_t meshtastic_LoBBSUser_msg;
extern const pb_msgdesc_t meshtastic_LoBBSSession_msg;
extern const pb_msgdesc_t meshtastic_LoBBSMail_msg;
extern const pb_msgdesc_t meshtastic_LoBBSNews_msg;
extern const pb_msgdesc_t meshtastic_LoBBSNewsRead_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meshtastic_LoBBSUser_fields &meshtastic_LoBBSUser_msg
#define meshtastic_LoBBSSession_fields &meshtastic_LoBBSSession_msg
#define meshtastic_LoBBSMail_fields &meshtastic_LoBBSMail_msg
#define meshtastic_LoBBSNews_fields &meshtastic_LoBBSNews_msg
#define meshtastic_LoBBSNewsRead_fields &meshtastic_LoBBSNewsRead_msg

/* Maximum encoded size of messages (where known) */
#define MESHTASTIC_LOBBS_PB_H_MAX_SIZE           meshtastic_LoBBSMail_size
#define meshtastic_LoBBSMail_size                243
#define meshtastic_LoBBSNewsRead_size            28
#define meshtastic_LoBBSNews_size                230
#define meshtastic_LoBBSSession_size             23
#define meshtastic_LoBBSUser_size                80

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
