/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "yarn.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(meshtastic_LoBBSYarnCurrent, meshtastic_LoBBSYarnCurrent, AUTO)


PB_BIND(meshtastic_LoBBSYarnSeen, meshtastic_LoBBSYarnSeen, AUTO)


PB_BIND(meshtastic_LoBBSYarnConfig, meshtastic_LoBBSYarnConfig, AUTO)


PB_BIND(meshtastic_LoBBSYarnQuota, meshtastic_LoBBSYarnQuota, AUTO)
