/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTIC_YARN_PB_H_INCLUDED
#define PB_MESHTASTIC_YARN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

typedef struct _meshtastic_LoBBSYarnCurrent {
    char text[186];
    uint32_t total_words_appended;
} meshtastic_LoBBSYarnCurrent;

typedef struct _meshtastic_LoBBSYarnSeen {
    uint64_t user_uuid;
    uint32_t last_seen_total_words;
} meshtastic_LoBBSYarnSeen;

typedef struct _meshtastic_LoBBSYarnConfig {
    uint32_t period_seconds;
    uint32_t max_words_per_interval;
    uint32_t max_chars_per_interval;
} meshtastic_LoBBSYarnConfig;

typedef struct _meshtastic_LoBBSYarnQuota {
    uint64_t user_uuid;
    uint32_t cycle_start;
    uint32_t words_used;
    uint32_t chars_used;
} meshtastic_LoBBSYarnQuota;

#ifdef __cplusplus
extern "C" {
#endif

#define meshtastic_LoBBSYarnCurrent_init_default  {"", 0}
#define meshtastic_LoBBSYarnSeen_init_default    {0, 0}
#define meshtastic_LoBBSYarnConfig_init_default  {0, 0, 0}
#define meshtastic_LoBBSYarnQuota_init_default   {0, 0, 0, 0}
#define meshtastic_LoBBSYarnCurrent_init_zero    {"", 0}
#define meshtastic_LoBBSYarnSeen_init_zero       {0, 0}
#define meshtastic_LoBBSYarnConfig_init_zero     {0, 0, 0}
#define meshtastic_LoBBSYarnQuota_init_zero      {0, 0, 0, 0}

#define meshtastic_LoBBSYarnCurrent_text_tag     1
#define meshtastic_LoBBSYarnCurrent_total_words_appended_tag 2
#define meshtastic_LoBBSYarnSeen_user_uuid_tag   1
#define meshtastic_LoBBSYarnSeen_last_seen_total_words_tag 2
#define meshtastic_LoBBSYarnConfig_period_seconds_tag 1
#define meshtastic_LoBBSYarnConfig_max_words_per_interval_tag 2
#define meshtastic_LoBBSYarnConfig_max_chars_per_interval_tag 3
#define meshtastic_LoBBSYarnQuota_user_uuid_tag  1
#define meshtastic_LoBBSYarnQuota_cycle_start_tag 2
#define meshtastic_LoBBSYarnQuota_words_used_tag 3
#define meshtastic_LoBBSYarnQuota_chars_used_tag 4

#define meshtastic_LoBBSYarnCurrent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1) \
X(a, STATIC,   SINGULAR, UINT32,   total_words_appended, 2)
#define meshtastic_LoBBSYarnCurrent_CALLBACK NULL
#define meshtastic_LoBBSYarnCurrent_DEFAULT NULL

#define meshtastic_LoBBSYarnSeen_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   user_uuid,         1) \
X(a, STATIC,   SINGULAR, UINT32,   last_seen_total_words, 2)
#define meshtastic_LoBBSYarnSeen_CALLBACK NULL
#define meshtastic_LoBBSYarnSeen_DEFAULT NULL

#define meshtastic_LoBBSYarnConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   period_seconds,    1) \
X(a, STATIC,   SINGULAR, UINT32,   max_words_per_interval, 2) \
X(a, STATIC,   SINGULAR, UINT32,   max_chars_per_interval, 3)
#define meshtastic_LoBBSYarnConfig_CALLBACK NULL
#define meshtastic_LoBBSYarnConfig_DEFAULT NULL

#define meshtastic_LoBBSYarnQuota_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   user_uuid,         1) \
X(a, STATIC,   SINGULAR, UINT32,   cycle_start,       2) \
X(a, STATIC,   SINGULAR, UINT32,   words_used,        3) \
X(a, STATIC,   SINGULAR, UINT32,   chars_used,        4)
#define meshtastic_LoBBSYarnQuota_CALLBACK NULL
#define meshtastic_LoBBSYarnQuota_DEFAULT NULL

extern const pb_msgdesc_t meshtastic_LoBBSYarnCurrent_msg;
extern const pb_msgdesc_t meshtastic_LoBBSYarnSeen_msg;
extern const pb_msgdesc_t meshtastic_LoBBSYarnConfig_msg;
extern const pb_msgdesc_t meshtastic_LoBBSYarnQuota_msg;

#define meshtastic_LoBBSYarnCurrent_fields &meshtastic_LoBBSYarnCurrent_msg
#define meshtastic_LoBBSYarnSeen_fields &meshtastic_LoBBSYarnSeen_msg
#define meshtastic_LoBBSYarnConfig_fields &meshtastic_LoBBSYarnConfig_msg
#define meshtastic_LoBBSYarnQuota_fields &meshtastic_LoBBSYarnQuota_msg

#define meshtastic_LoBBSYarnCurrent_size           194
#define meshtastic_LoBBSYarnSeen_size              17
#define meshtastic_LoBBSYarnConfig_size            18
#define meshtastic_LoBBSYarnQuota_size             28

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
