/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTIC_AUTH_PB_H_INCLUDED
#define PB_MESHTASTIC_AUTH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(32) meshtastic_LoBBSUser_password_hash_t;
/* LoBBS User Record
 Stores user authentication information for the LoBBS system
 UUID: username (for direct lookups) */
typedef struct _meshtastic_LoBBSUser {
    /* Username for the user account */
    char username[32];
    /* SHA256 hash of the user's password (32 bytes) */
    meshtastic_LoBBSUser_password_hash_t password_hash;
    /* User UUID - deterministic hash derived from username */
    uint64_t uuid;
    /* Whether this user is a SysOp (system operator) */
    bool is_sysop;
} meshtastic_LoBBSUser;

/* LoBBS Session Record
 Maps node IDs to logged-in user UUIDs
 UUID: node ID as uint64 */
typedef struct _meshtastic_LoBBSSession {
    /* User UUID of the logged-in user */
    uint64_t user_uuid;
    /* Last login timestamp */
    uint32_t last_login_time;
    /* Node ID (stored for reference) */
    uint32_t node_id;
} meshtastic_LoBBSSession;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meshtastic_LoBBSUser_init_default        {"", {0, {0}}, 0, 0}
#define meshtastic_LoBBSSession_init_default     {0, 0, 0}
#define meshtastic_LoBBSUser_init_zero           {"", {0, {0}}, 0, 0}
#define meshtastic_LoBBSSession_init_zero        {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define meshtastic_LoBBSUser_username_tag        1
#define meshtastic_LoBBSUser_password_hash_tag   2
#define meshtastic_LoBBSUser_uuid_tag            3
#define meshtastic_LoBBSUser_is_sysop_tag        4
#define meshtastic_LoBBSSession_user_uuid_tag    1
#define meshtastic_LoBBSSession_last_login_time_tag 2
#define meshtastic_LoBBSSession_node_id_tag      3

/* Struct field encoding specification for nanopb */
#define meshtastic_LoBBSUser_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   username,          1) \
X(a, STATIC,   SINGULAR, BYTES,    password_hash,     2) \
X(a, STATIC,   SINGULAR, UINT64,   uuid,              3) \
X(a, STATIC,   SINGULAR, BOOL,     is_sysop,          4)
#define meshtastic_LoBBSUser_CALLBACK NULL
#define meshtastic_LoBBSUser_DEFAULT NULL

#define meshtastic_LoBBSSession_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   user_uuid,         1) \
X(a, STATIC,   SINGULAR, UINT32,   last_login_time,   2) \
X(a, STATIC,   SINGULAR, UINT32,   node_id,           3)
#define meshtastic_LoBBSSession_CALLBACK NULL
#define meshtastic_LoBBSSession_DEFAULT NULL

extern const pb_msgdesc_t meshtastic_LoBBSUser_msg;
extern const pb_msgdesc_t meshtastic_LoBBSSession_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meshtastic_LoBBSUser_fields &meshtastic_LoBBSUser_msg
#define meshtastic_LoBBSSession_fields &meshtastic_LoBBSSession_msg

/* Maximum encoded size of messages (where known) */
#define MESHTASTIC_AUTH_PB_H_MAX_SIZE            meshtastic_LoBBSUser_size
#define meshtastic_LoBBSSession_size             23
#define meshtastic_LoBBSUser_size                80

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
